#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Persia.Resource", IsApplication=true)]

namespace Persia
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BarraImagen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Camara = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IconoDeco = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IconoElectronica = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IconoFacebook = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IconoFlicker = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IconoJuegos = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IconoLibros = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IconoMuebles = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IconoMusica = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IconoOtros = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IconoPeliculas = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IconoRopa = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IconoTumblr = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IconoTwitter = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ImagenFotoSillon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Inicio = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int LoginFacebook = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int PersiaLogoTempo = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040016
			public const int BotonActivarFacebook = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int BotonActivarFlickr = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int BotonActivarTumblr = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int BotonActivarTwitter = 2130968599;
			
			// aapt resource value: 0x7f040007
			public const int BotonAtras = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int BotonBack = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int BotonBuscar = 2130968579;
			
			// aapt resource value: 0x7f040014
			public const int BotonCancelar = 2130968596;
			
			// aapt resource value: 0x7f04000d
			public const int BotonCategoriaDeco = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int BotonCategoriaElectronica = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int BotonCategoriaJuegos = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int BotonCategoriaLibros = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int BotonCategoriaMuebles = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int BotonCategoriaMusica = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int BotonCategoriaOtros = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int BotonCategoriaPeliculas = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int BotonCategoriaRopa = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int BotonElegirFoto = 2130968594;
			
			// aapt resource value: 0x7f040004
			public const int BotonHamburguesa = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int BotonHome = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int BotonMensajes = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int BotonPerfil = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int BotonPublicar = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int BotonPublicarNuevo = 2130968602;
			
			// aapt resource value: 0x7f040011
			public const int BotonSubirFoto = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int BotonTomarFoto = 2130968595;
			
			// aapt resource value: 0x7f040001
			public const int BottonPublicarNuevo = 2130968577;
			
			// aapt resource value: 0x7f040021
			public const int descripcionPublicacion = 2130968609;
			
			// aapt resource value: 0x7f040023
			public const int editText1 = 2130968611;
			
			// aapt resource value: 0x7f04001b
			public const int imageFondo = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int imageView1 = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int imageView2 = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int linearLayout1 = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int tablaBotonesCategoria = 2130968612;
			
			// aapt resource value: 0x7f040022
			public const int tableRow1 = 2130968610;
			
			// aapt resource value: 0x7f040025
			public const int tableRow2 = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int tableRow3 = 2130968614;
			
			// aapt resource value: 0x7f04001f
			public const int textView1 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int tituloPublicacion = 2130968608;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginFacebook = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Principal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int VentanaCrearPublicacion = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VentanaElegirCategoria = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int VentanaSubirFoto = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int login = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
